"""review and pitch Migration

Revision ID: 2f674d6d3a4b
Revises: f28916c1e95e
Create Date: 2018-06-28 11:18:13.831013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f674d6d3a4b'
down_revision = 'f28916c1e95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_pitch_username'), 'pitch', ['username'], unique=False)
    op.add_column('review', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_review_username'), 'review', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_username'), table_name='review')
    op.drop_column('review', 'username')
    op.drop_index(op.f('ix_pitch_username'), table_name='pitch')
    op.drop_column('pitch', 'username')
    # ### end Alembic commands ###
